# Default VulnMiner Configuration
# This is the base configuration file that defines default settings

# System Configuration
system:
  debug: false
  max_concurrent_scans: 5
  timeout: 300
  max_scan_runtime: 3600  # 1 hour maximum per scan
  
# Database Configuration
database:
  path: "data/scans.db"
  retention_days: 90
  
# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/vulnminer.log"
  structured: true
  
# Security Configuration
security:
  ssl_verification: true
  authorization:
    enabled: true
    whitelist_only: true
    authorized_targets: []
  rate_limiting:
    enabled: true
    max_requests_per_minute: 60
    max_requests_per_hour: 1000
  scan_restrictions:
    allowed_scan_types: []  # Empty means all types allowed
    forbidden_scan_types: []
    aggressive_scan_types: ["exploitation"]
  target_safety:
    allow_localhost: false
    allow_private_networks: true
  aggressive_scan_targets: []  # Targets explicitly authorized for aggressive scans

# Tool Configuration
tools:
  db_path: "data/tools.db"
  usage_retention_days: 30
  
  # Nmap Configuration
  nmap:
    enabled: true
    path: null  # Auto-detect
    version: "latest"
    config:
      default_args: ["-sS", "-O", "-sV"]
      timing_template: 3
      max_targets: 100
      
  # Nuclei Configuration
  nuclei:
    enabled: true
    path: null  # Auto-detect
    version: "latest"
    config:
      templates_path: "nuclei-templates"
      severity_levels: ["info", "low", "medium", "high", "critical"]
      max_templates: 1000
      
  # HTTPx Configuration
  httpx:
    enabled: true
    path: null
    version: "latest"
    config:
      timeout: 10
      threads: 50
      
  # Subfinder Configuration
  subfinder:
    enabled: true
    path: null
    version: "latest"
    config:
      timeout: 30
      
  # Gobuster Configuration
  gobuster:
    enabled: true
    path: null
    version: "latest"
    config:
      wordlists_path: "wordlists"
      default_wordlist: "common.txt"
      threads: 10

# Scan Pipeline Configuration
pipelines:
  # Quick scan pipeline for fast reconnaissance
  quick:
    discovery:
      tools:
        - name: nmap
          args:
            scan_type: fast
            ports: "22,80,443,8080,8443"
            timeout: 60
          timeout: 60
      parallel: false
      timeout: 120
      continue_on_error: true
      
    vulnerability_scan:
      tools:
        - name: nuclei
          args:
            severity: "medium,high,critical"
            tags: "cve,owasp,rce,sqli,xss"
            timeout: 300
          timeout: 300
      parallel: false
      timeout: 400
      continue_on_error: true
  
  # Comprehensive scan pipeline for thorough analysis
  comprehensive:
    discovery:
      tools:
        - name: nmap
          args:
            scan_type: comprehensive
            ports: "1-65535"
            service_version: true
            os_detection: true
            timeout: 600
          timeout: 600
      parallel: false
      timeout: 800
      continue_on_error: true
      
    enumeration:
      tools:
        - name: subfinder
          args:
            passive: true
            timeout: 180
          timeout: 180
        - name: httpx
          args:
            probe: true
            status_code: true
            content_length: true
            timeout: 10
          timeout: 120
      parallel: true
      timeout: 400
      continue_on_error: true
      
    vulnerability_scan:
      tools:
        - name: nuclei
          args:
            severity: "low,medium,high,critical"
            timeout: 900
            rate_limit: 150
          timeout: 900
      parallel: false
      timeout: 1000
      continue_on_error: true
  
  # Web application focused scan pipeline
  webapp:
    discovery:
      tools:
        - name: httpx
          args:
            probe: true
            status_code: true
            tech_detect: true
            timeout: 10
          timeout: 60
      parallel: false
      timeout: 120
      continue_on_error: true
      
    enumeration:
      tools:
        - name: gobuster
          args:
            mode: dir
            wordlist: web-common
            extensions: "php,html,js,txt,xml,json"
            status_codes: "200,204,301,302,307,401,403"
            timeout: 300
          timeout: 300
        - name: subfinder
          args:
            passive: true
            timeout: 120
          timeout: 120
      parallel: true
      timeout: 400
      continue_on_error: true
      
    vulnerability_scan:
      tools:
        - name: nuclei
          args:
            tags: "web,owasp,cve"
            severity: "medium,high,critical"
            timeout: 600
            rate_limit: 100
          timeout: 600
      parallel: false
      timeout: 800
      continue_on_error: true

# Result Aggregation Configuration
aggregation:
  duplicate_threshold: 0.8  # Similarity threshold for duplicate detection
  correlation_window: 300   # Time window in seconds for correlating findings
  confidence_threshold: 0.7 # Minimum confidence for high-value findings
  
# Constraints and Limits
constraints:
  rate_limiting:
    enabled: true
    max_requests_per_second: 10
    burst_allowance: 50
    
  timeout:
    default: 300
    maximum: 3600
    
  concurrent_scans:
    maximum: 5
    per_target: 1
    
  resource_limits:
    max_memory_mb: 2048
    max_cpu_percent: 80
    max_disk_usage_mb: 5000